# Generated by Django 5.1.6 on 2025-03-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_or_zip_code',
            field=models.CharField(blank=True, default=None, max_length=16),
        ),
    ]
