# Generated by Django 5.2.8 on 2026-06-23 17:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('execution_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order')], max_length=6)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Required for LIMIT orders only', max_digits=12, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='creature.creature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Weighted average purchase price per unit', max_digits=12)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='creature.creature')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'portfolios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Total units traded in this interval', max_digits=18)),
                ('interval', models.CharField(choices=[('1H', '1 Hour'), ('1D', '1 Day'), ('1W', '1 Week')], max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='creature.creature')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, help_text='Actual commission charged at execution time', max_digits=12)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_as_buy', to='trading.order')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='creature.creature')),
                ('sell_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_as_sell', to='trading.order')),
                ('seller', models.ForeignKey(blank=True, help_text='NULL when the Market Maker (liquidity pool) is the counterparty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['creature', 'status', 'order_type'], name='trading_ord_creatur_83cf81_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', 'status'], name='trading_ord_account_f89586_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('owner', 'creature')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['creature', 'interval', 'timestamp'], name='trading_pri_creatur_c22553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('creature', 'interval', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['creature', 'executed_at'], name='trading_tra_creatur_a1d1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['buyer', 'executed_at'], name='trading_tra_buyer_i_40e79a_idx'),
        ),
    ]
