# Generated by Django 5.2.8 on 2026-06-24 00:18

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creature_type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_volume', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Total trading volume across all creatures in this index', max_digits=18)),
                ('creature_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'market indices',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['creature_type', 'timestamp'], name='trading_mar_creatur_a56e3d_idx')],
            },
        ),
    ]
