# Generated by Django 5.2.8 on 2026-06-24 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0003_creature_circuit_breaker_expires_at'),
        ('trading', '0002_marketindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('VOLATILITY', 'Volatility Alert'), ('BATTLE', 'Battle Result'), ('INCUBATION', 'Incubation Complete'), ('TRAINING', 'Training Complete'), ('SYSTEM', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_creature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creature.creature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='trading_not_user_id_7486d2_idx')],
            },
        ),
    ]
