# Generated by Django 5.2.7 on 2025-10-05 01:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('EARTH', 'Earth')], max_length=10)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('large_icon_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'creature',
                'verbose_name_plural': 'creatures',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='creature_cr_symbol_bc85ba_idx'), models.Index(fields=['current_price'], name='creature_cr_current_e78bcd_idx')],
            },
        ),
    ]
