# Generated by Django 5.2.8 on 2026-03-03 22:44

import creature.models
import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('ability_type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15)),
                ('power', models.PositiveIntegerField(blank=True, help_text='Base power of the move', null=True)),
                ('accuracy', models.PositiveIntegerField(default=100, help_text='Accuracy percentage (0-100)')),
                ('pp', models.PositiveIntegerField(default=20, help_text='Power Points - how many times the move can be used')),
                ('priority', models.IntegerField(default=0, help_text='Move priority (higher goes first)')),
                ('damage_class', models.CharField(choices=[('physical', 'Physical'), ('special', 'Special'), ('status', 'Status')], help_text='Physical, Special, or Status move', max_length=10)),
                ('target', models.CharField(choices=[('self', 'Self'), ('single_opponent', 'Single Opponent'), ('single_ally', 'Single Ally'), ('all_opponents', 'All Opponents'), ('all_allies', 'All Allies'), ('all', 'All'), ('random_opponent', 'Random Opponent'), ('field', 'Field')], default='single_opponent', max_length=20)),
                ('makes_contact', models.BooleanField(default=False, help_text='Whether the move makes physical contact')),
                ('is_healing_move', models.BooleanField(default=False)),
                ('healing_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of HP healed (if healing move)')),
                ('chance_to_inflict_status', models.PositiveIntegerField(default=0, help_text='Chance to inflict status condition (0-100)')),
                ('generation_introduced', models.PositiveIntegerField(default=1)),
                ('is_signature_move', models.BooleanField(default=False, help_text='Whether this is a signature move for specific creatures')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], default='pending', max_length=10)),
                ('current_turn', models.PositiveIntegerField(default=1)),
                ('battle_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField(default=0)),
                ('attack_stage', models.IntegerField(default=0)),
                ('defense_stage', models.IntegerField(default=0)),
                ('status_ailment', models.CharField(blank=True, max_length=20, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='creature.battle')),
            ],
        ),
        migrations.CreateModel(
            name='BattleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('is_item', models.BooleanField(default=False)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creature.ability')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='creature.battle')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_performed', to='creature.battleparticipant')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to='creature.battleparticipant')),
            ],
            options={
                'ordering': ['turn_number', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='creature.battleparticipant'),
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15)),
                ('secondary_type', models.CharField(blank=True, choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15, null=True)),
                ('current_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hp', models.PositiveIntegerField(default=20)),
                ('attack', models.PositiveIntegerField(default=10)),
                ('defense', models.PositiveIntegerField(default=55)),
                ('special_attack', models.PositiveIntegerField(default=15)),
                ('special_defense', models.PositiveIntegerField(default=20)),
                ('speed', models.PositiveIntegerField(default=80)),
                ('evolution_level', models.PositiveIntegerField(blank=True, null=True)),
                ('is_legendary', models.BooleanField(default=False)),
                ('is_mythical', models.BooleanField(default=False)),
                ('battle_cooldown', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('cooldown_expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('currently_in_battle', models.BooleanField(default=False)),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path, verbose_name='Creature Small Icon')),
                ('large_icon', models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path, verbose_name='Creature Large Icon')),
                ('abilities', models.ManyToManyField(blank=True, related_name='creatures', to='creature.ability')),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_to', to='creature.creature')),
            ],
            options={
                'verbose_name': 'creature',
                'verbose_name_plural': 'creatures',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creature.creature'),
        ),
        migrations.AddIndex(
            model_name='creature',
            index=models.Index(fields=['current_price'], name='creature_cr_current_e78bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='creature',
            index=models.Index(fields=['type'], name='creature_cr_type_83f45f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battleparticipant',
            unique_together={('battle', 'creature')},
        ),
    ]
