# Generated by Django 5.2.8 on 2025-11-19 00:39

import creature.models
import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('ability_type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15)),
                ('power', models.PositiveIntegerField(blank=True, help_text='Base power of the move', null=True)),
                ('accuracy', models.PositiveIntegerField(default=100, help_text='Accuracy percentage (0-100)')),
                ('pp', models.PositiveIntegerField(default=20, help_text='Power Points - how many times the move can be used')),
                ('priority', models.IntegerField(default=0, help_text='Move priority (higher goes first)')),
                ('damage_class', models.CharField(choices=[('physical', 'Physical'), ('special', 'Special'), ('status', 'Status')], help_text='Physical, Special, or Status move', max_length=10)),
                ('target', models.CharField(choices=[('self', 'Self'), ('single_opponent', 'Single Opponent'), ('single_ally', 'Single Ally'), ('all_opponents', 'All Opponents'), ('all_allies', 'All Allies'), ('all', 'All'), ('random_opponent', 'Random Opponent'), ('field', 'Field')], default='single_opponent', max_length=20)),
                ('makes_contact', models.BooleanField(default=False, help_text='Whether the move makes physical contact')),
                ('is_healing_move', models.BooleanField(default=False)),
                ('healing_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of HP healed (if healing move)')),
                ('chance_to_inflict_status', models.PositiveIntegerField(default=0, help_text='Chance to inflict status condition (0-100)')),
                ('stat_changes', models.JSONField(default=dict, help_text='JSON format: {"attack": 1, "defense": -1} for stat changes')),
                ('generation_introduced', models.PositiveIntegerField(default=1)),
                ('is_signature_move', models.BooleanField(default=False, help_text='Whether this is a signature move for specific creatures')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField()),
                ('battle_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15)),
                ('secondary_type', models.CharField(blank=True, choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('normal', 'Normal'), ('flying', 'Flying'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('poison', 'Poison')], max_length=15, null=True)),
                ('current_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hp', models.PositiveIntegerField(default=50)),
                ('attack', models.PositiveIntegerField(default=50)),
                ('defense', models.PositiveIntegerField(default=50)),
                ('special_attack', models.PositiveIntegerField(default=50)),
                ('special_defense', models.PositiveIntegerField(default=50)),
                ('speed', models.PositiveIntegerField(default=50)),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=4)),
                ('height', models.FloatField(default=1.0, help_text='Height in meters')),
                ('weight', models.FloatField(default=10.0, help_text='Weight in kilograms')),
                ('evolution_level', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_introduced', models.PositiveIntegerField(default=1)),
                ('is_legendary', models.BooleanField(default=False)),
                ('is_mythical', models.BooleanField(default=False)),
                ('battle_cooldown', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path, verbose_name='Creature Small Icon')),
                ('large_icon', models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path, verbose_name='Creature Large Icon')),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_to', to='creature.creature')),
            ],
            options={
                'verbose_name': 'creature',
                'verbose_name_plural': 'creatures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.BooleanField(default=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creature.battle')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creature.creature')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='creatures',
            field=models.ManyToManyField(related_name='battles', through='creature.BattleParticipant', through_fields=('battle', 'creature'), to='creature.creature'),
        ),
        migrations.AddIndex(
            model_name='creature',
            index=models.Index(fields=['current_price'], name='creature_cr_current_e78bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='creature',
            index=models.Index(fields=['type'], name='creature_cr_type_83f45f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battleparticipant',
            unique_together={('battle', 'creature')},
        ),
    ]
