# Generated by Django 5.2.8 on 2026-06-24 00:12

import creature.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hatch_duration', models.DurationField(help_text='Real time until the egg hatches (e.g. 1 hour)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('creature_pool', models.ManyToManyField(help_text='Possible creatures that can hatch from this egg', related_name='egg_templates', to='creature.creature')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INCUBATING', 'Incubating'), ('HATCHED', 'Hatched')], default='INCUBATING', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('hatches_at', models.DateTimeField()),
                ('hatched_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for the hatch timer', max_length=255, null=True)),
                ('egg_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubations', to='creature.eggtemplate')),
                ('hatched_creature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatched_from', to='creature.creature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
