# Generated by Django 5.2.6 on 2025-10-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
