# Generated by Django 5.2.8 on 2025-11-24 20:47

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='stat_changes',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='generation_introduced',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='height',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='weight',
        ),
        migrations.AlterField(
            model_name='creature',
            name='abilities',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=4),
        ),
        migrations.AlterField(
            model_name='creature',
            name='attack',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='creature',
            name='defense',
            field=models.PositiveIntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='creature',
            name='hp',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='creature',
            name='special_attack',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='creature',
            name='special_defense',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='creature',
            name='speed',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
