# Generated by Django 5.2.8 on 2025-11-25 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0002_remove_ability_stat_changes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='outcome',
        ),
        migrations.AddField(
            model_name='creature',
            name='currently_in_battle',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BattleOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField()),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battleOutcomes', to='creature.battle')),
            ],
        ),
    ]
