# Generated by Django 5.2.8 on 2026-06-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0002_eggtemplate_incubation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='circuit_breaker_expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, trading is frozen until this time (volatility halt)', null=True),
        ),
    ]
