# Generated by Django 5.2.6 on 2025-10-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0002_creature_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='large_icon_url',
        ),
        migrations.AddField(
            model_name='creature',
            name='large_icon',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AddField(
            model_name='creature',
            name='small_icon',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
    ]
