# Generated by Django 5.2.6 on 2025-10-12 00:22

import creature.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0003_remove_creature_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='large_icon',
            field=models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path, verbose_name='Creature Large Icon'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='small_icon',
            field=models.ImageField(blank=True, null=True, upload_to=creature.models.creature_image_upload_path, verbose_name='Creature Small Icon'),
        ),
    ]
