# Generated by Django 5.2.8 on 2026-06-24 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0003_creature_circuit_breaker_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='creature_1_elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='creature_1_elo_before',
            field=models.IntegerField(default=1000, help_text='ELO snapshot — backend only, never exposed'),
        ),
        migrations.AddField(
            model_name='battle',
            name='creature_1_potential_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-computed potential price change % if creature_1 wins', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='creature_2_elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='creature_2_elo_before',
            field=models.IntegerField(default=1000, help_text='ELO snapshot — backend only, never exposed'),
        ),
        migrations.AddField(
            model_name='battle',
            name='creature_2_potential_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-computed potential price change % if creature_2 wins', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='next_turn_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the next turn will be processed'),
        ),
        migrations.AddField(
            model_name='creature',
            name='elo_rating',
            field=models.IntegerField(default=1000, help_text='Internal ELO rating for battle valuation — never exposed to users'),
        ),
        migrations.AddField(
            model_name='creature',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BattleInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('investor_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='creature.battle')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creature.creature')),
            ],
            options={
                'ordering': ['turn_number'],
                'unique_together': {('battle', 'turn_number', 'creature')},
            },
        ),
    ]
