# Generated by Django 5.2.6 on 2025-10-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0004_alter_creature_large_icon_alter_creature_small_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ['name'], 'verbose_name': 'creature', 'verbose_name_plural': 'creatures'},
        ),
        migrations.RemoveIndex(
            model_name='creature',
            name='creature_cr_symbol_bc85ba_idx',
        ),
        migrations.AddIndex(
            model_name='creature',
            index=models.Index(fields=['type'], name='creature_cr_type_83f45f_idx'),
        ),
    ]
