# Generated by Django 5.2.8 on 2026-06-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0004_battle_elo_rating_turn_timing_and_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='battle_log',
        ),
        migrations.RemoveField(
            model_name='battleaction',
            name='description',
        ),
    ]
