# Generated by Django 5.2.6 on 2025-10-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0005_alter_creature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='symbol',
        ),
    ]
