# Generated by Django 5.2.8 on 2026-06-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0005_remove_battle_log_and_action_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleparticipant',
            name='price_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Creature price after battle finished', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='price_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Creature price when battle started', max_digits=12, null=True),
        ),
    ]
