# Generated by Django 5.2.8 on 2026-01-18 23:32

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=20, prefix='TRN', unique=True)),
                ('type', models.CharField(choices=[('TRANSFER', 'Transfer between users'), ('DEPOSIT', 'External deposit'), ('WITHDRAW', 'External withdraw')], max_length=20)),
                ('status', models.CharField(choices=[('failed', 'Transaction rejected'), ('pending', 'The transaction is being processed'), ('completed', 'Transaction completed')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
